spring:
    datasource:
        name: test
        url: jdbc:mysql://123.206.28.120:3306/yd_platfrom
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    type-aliases-package: com.yunding.pojo
    mapper-locations: classpath:mapper/*.xml
